version: "3"

services:
  
  pipeline-zookeeper-a:
    image: makengi12/zookeeper:1.0
    container_name: pipeline-zookeeper-a 
    restart: always 
    hostname: pipeline-zookeeper-a 
    environment: 
        MY_ID: 1 
    volumes: 
      - pipeline-zookeeper-a-volume:/data

  pipeline-zookeeper-b: 
    image: makengi12/zooekeeper:1.0
    container_name: pipeline-zookeeper-b 
    restart: always 
    hostname: pipeline-zookeeper-b 
    environment: 
        MY_ID: 2 
    volumes: 
      - pipeline-zookeeper-b-volume:/data 
    
  pipeline-zookeeper-c: 
    image: makengi12/zookeeper:1.0
    container_name: pipeline-zookeeper-c 
    restart: always 
    hostname: pipeline-zookeeper-c 
    environment: 
      MY_ID: 3 
    volumes: 
      - pipeline-zookeeper-c-volume:/data


volumes:
  pipeline-zookeeper-a-volume:
  pipeline-zookeeper-b-volume:   
  pipeline-zookeeper-c-volume:
         